version: '3.8'
services:
  database:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-shared-dev
      - MONGO_INITDB_ROOT_PASSWORD=fikTpih4U2!
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo-shared-dev:fikTpih4U2!@database:27017/?authSource=admin
    depends_on:
      - database
    networks:
      - app-network
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data: